\c almaren;


CREATE TABLE public.column_profile
(
    dataplace_id integer,
    schema_id bigint,
    table_id bigint,
    datastore_id bigint,
    datastore_table_id bigint,
    column_id bigint,
    profile_id bigint,
    prev_profile_id bigint,
    fuzzy_index text COLLATE pg_catalog."default",
    valid_from_ts text COLLATE pg_catalog."default",
    valid_to_ts text COLLATE pg_catalog."default",
    column_name text COLLATE pg_catalog."default",
    ordinal_position smallint,
    column_datatype text COLLATE pg_catalog."default",
    total_count bigint,
    non_null_count bigint,
    null_count bigint,
    distinct_count bigint,
    is_numeric boolean,
    num_of_spaces bigint,
    min text COLLATE pg_catalog."default",
    max text COLLATE pg_catalog."default",
    avg text COLLATE pg_catalog."default",
    min_string_length integer,
    max_string_length integer,
    empty_string_count bigint,
    non_empty_string_count bigint,
    avg_string_length bigint,
    has_date boolean,
    date_format text COLLATE pg_catalog."default",
    selectivity numeric,
    cardinality numeric,
    numeric_count bigint,
    median text COLLATE pg_catalog."default",
    standard_deviation text COLLATE pg_catalog."default",
    crt_by text COLLATE pg_catalog."default",
    crt_ts text COLLATE pg_catalog."default",
    mod_by text COLLATE pg_catalog."default",
    mod_ts text COLLATE pg_catalog."default",
    table_name text COLLATE pg_catalog."default"
)
